//
// Created by Martin Edviken on 2022-08-05.
//

#ifndef GAMEBOYEMULATOR_MEMORYBANKCONTROLLER_HPP
#define GAMEBOYEMULATOR_MEMORYBANKCONTROLLER_HPP


class MemoryBankController {

};


#endif //GAMEBOYEMULATOR_MEMORYBANKCONTROLLER_HPP
