name: 'build-test'

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'feature/**'
      - 'bugfix/**'
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      # build project
      - name: mkdir
        run: mkdir build
      - name: cmake build
        run: cmake -B build -H.
      - name: cmake make
        run: cmake --build build/ --target all
      # run tests
      - name: run test CartridgeInterpreterTest
        run: build/test/CartridgeInterpreterTest
